<a href="https://colab.research.google.com/github/gi-junqueira/Calculo-Numerico/blob/main/sistemas_lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sistemas lineares e implementação numérica
**Integrantes**: Leonardo Tomasela Leal (170291), Giovanna Maria de Siqueira Junqueira (185218) e Guilherme Miguel Spyrides Leite Ferro (176466)

---


Resolução completa das Partes 1 a 4. As passagens manuais estão em LaTeX (células Markdown) e as implementações em Python (células de código comentadas), com resultados e breve interpretação.

## Parte 1 — Conceitos e resolução manual

### Exercício 1 — Sistemas lineares na forma matricial

Todo sistema linear com $n$ equações e $n$ incógnitas pode ser escrito como $A\mathbf{x}=\mathbf{b}$, em que $A$ é a matriz dos coeficientes, $\mathbf{x}$ o vetor de incógnitas e $\mathbf{b}$ o vetor independente.

**a)**
$$
\begin{cases} 2x+y=7\\ x-3y=-5 \end{cases}
\quad\Longrightarrow\quad
\underbrace{\begin{bmatrix} 2 & 1\\ 1 & -3 \end{bmatrix}}_{A}
\underbrace{\begin{bmatrix} x\\ y \end{bmatrix}}_{\mathbf{x}}
=
\underbrace{\begin{bmatrix} 7\\ -5 \end{bmatrix}}_{\mathbf{b}}
$$

**b)**
$$
\begin{cases} x+2y-z=2\\ 3x-y+2z=9\\ 2x+y+z=7 \end{cases}
\quad\Longrightarrow\quad
\underbrace{\begin{bmatrix} 1 & 2 & -1\\ 3 & -1 & 2\\ 2 & 1 & 1 \end{bmatrix}}_{A}
\underbrace{\begin{bmatrix} x\\ y\\ z \end{bmatrix}}_{\mathbf{x}}
=
\underbrace{\begin{bmatrix} 2\\ 9\\ 7 \end{bmatrix}}_{\mathbf{b}}
$$

### Exercício 2 — Eliminação de Gauss

$$
\begin{cases} 2x+y-z=8\\ -3x-y+2z=-11\\ -2x+y+2z=-3 \end{cases}
$$

**Matriz aumentada inicial:**
$$
\left[\begin{array}{rrr|r}
2 & 1 & -1 & 8\\
-3 & -1 & 2 & -11\\
-2 & 1 & 2 & -3
\end{array}\right]
$$

**Etapa 1 — eliminar a 1ª coluna abaixo do pivô $a_{11}=2$.**
Multiplicadores: $m_{21}=\frac{-3}{2}=-\frac32$ e $m_{31}=\frac{-2}{2}=-1$.

$L_2 \leftarrow L_2 + \tfrac32 L_1,\qquad L_3 \leftarrow L_3 + L_1$

$$
\left[\begin{array}{rrr|r}
2 & 1 & -1 & 8\\
0 & \tfrac12 & \tfrac12 & 1\\
0 & 2 & 1 & 5
\end{array}\right]
$$

**Etapa 2 — eliminar a 2ª coluna abaixo do pivô $a_{22}=\tfrac12$.**
Multiplicador: $m_{32}=\frac{2}{1/2}=4$.

$L_3 \leftarrow L_3 - 4L_2$

$$
\left[\begin{array}{rrr|r}
2 & 1 & -1 & 8\\
0 & \tfrac12 & \tfrac12 & 1\\
0 & 0 & -1 & 1
\end{array}\right]
$$

**Substituição regressiva:**
$$
-z = 1 \;\Rightarrow\; z=-1
$$
$$
\tfrac12 y + \tfrac12 z = 1 \;\Rightarrow\; \tfrac12 y = 1+\tfrac12 \;\Rightarrow\; y=3
$$
$$
2x + y - z = 8 \;\Rightarrow\; 2x = 8-3-1=4 \;\Rightarrow\; x=2
$$

**Verificação na 2ª e 3ª equações originais:**
$-3(2)-3+2(-1)=-6-3-2=-11$ ✓ e $-2(2)+3+2(-1)=-4+3-2=-3$ ✓

$$
\boxed{\mathbf{x}=(x,y,z)=(2,\;3,\;-1)}
$$

## Parte 2 — Propriedades e interpretação

### Exercício 3 — Número de soluções

**a)** $\begin{cases} x+y=3\\ 2x+2y=6 \end{cases}$

$$
\left[\begin{array}{rr|r} 1 & 1 & 3\\ 2 & 2 & 6 \end{array}\right]
\xrightarrow{L_2\leftarrow L_2-2L_1}
\left[\begin{array}{rr|r} 1 & 1 & 3\\ 0 & 0 & 0 \end{array}\right]
$$

A segunda linha se anula ($0=0$): há apenas uma equação independente para duas incógnitas, ou seja, $\operatorname{posto}(A)=\operatorname{posto}([A|b])=1<2$.
**Infinitas soluções:** $x=3-y$, com $y\in\mathbb{R}$ livre.

---

**b)** $\begin{cases} x+y=3\\ 2x+2y=7 \end{cases}$

$$
\left[\begin{array}{rr|r} 1 & 1 & 3\\ 2 & 2 & 7 \end{array}\right]
\xrightarrow{L_2\leftarrow L_2-2L_1}
\left[\begin{array}{rr|r} 1 & 1 & 3\\ 0 & 0 & 1 \end{array}\right]
$$

A segunda linha equivale a $0=1$, uma contradição: $\operatorname{posto}(A)=1\neq\operatorname{posto}([A|b])=2$.
**Nenhuma solução** (sistema incompatível).

---

**c)** $\begin{cases} x+y=3\\ 2x-y=0 \end{cases}$

$$
\left[\begin{array}{rr|r} 1 & 1 & 3\\ 2 & -1 & 0 \end{array}\right]
\xrightarrow{L_2\leftarrow L_2-2L_1}
\left[\begin{array}{rr|r} 1 & 1 & 3\\ 0 & -3 & -6 \end{array}\right]
$$

$-3y=-6\Rightarrow y=2$ e $x+2=3\Rightarrow x=1$. Aqui $\operatorname{posto}(A)=\operatorname{posto}([A|b])=2=n$.
**Solução única:** $(x,y)=(1,\,2)$.

**Resumo:**

| Sistema | $\operatorname{posto}(A)$ | $\operatorname{posto}([A\mid b])$ | Classificação |
|:--:|:--:|:--:|:--|
| a) | 1 | 1 | Infinitas soluções |
| b) | 1 | 2 | Nenhuma solução |
| c) | 2 | 2 | Solução única |

**Conferência computacional (opcional)** dos postos de cada sistema do exercício 3:

In [1]:
import numpy as np

# Sistemas do exercício 3: (A, b)
sistemas = {
    "a) x+y=3, 2x+2y=6": (np.array([[1, 1], [2, 2]], float), np.array([3, 6], float)),
    "b) x+y=3, 2x+2y=7": (np.array([[1, 1], [2, 2]], float), np.array([3, 7], float)),
    "c) x+y=3, 2x-y=0":  (np.array([[1, 1], [2, -1]], float), np.array([3, 0], float)),
}

for nome, (A, b) in sistemas.items():
    r_A = np.linalg.matrix_rank(A)                         # posto de A
    r_Ab = np.linalg.matrix_rank(np.column_stack([A, b]))  # posto da matriz aumentada
    n = A.shape[1]                                         # número de incógnitas
    if r_A != r_Ab:
        tipo = "nenhuma solução"
    elif r_A == n:
        tipo = "solução única"
    else:
        tipo = "infinitas soluções"
    print(f"{nome:22s} posto(A)={r_A}, posto([A|b])={r_Ab} -> {tipo}")

a) x+y=3, 2x+2y=6      posto(A)=1, posto([A|b])=1 -> infinitas soluções
b) x+y=3, 2x+2y=7      posto(A)=1, posto([A|b])=2 -> nenhuma solução
c) x+y=3, 2x-y=0       posto(A)=2, posto([A|b])=2 -> solução única


**Interpretação:** os postos calculados coincidem com a redução manual. Geometricamente, em (a) as duas retas são coincidentes, em (b) são paralelas distintas e em (c) são concorrentes em $(1,2)$.

## Parte 3 — Implementação numérica em Python

### Exercício 4 — Eliminação de Gauss sem pivoteamento

**Algoritmo.** Dada $A\in\mathbb{R}^{n\times n}$ e $\mathbf{b}\in\mathbb{R}^{n}$:

1. Formar a matriz aumentada $[A\,|\,\mathbf{b}]$.
2. Para cada coluna $k=0,\dots,n-2$ (pivô $a_{kk}$): para cada linha $i>k$, calcular $m_{ik}=a_{ik}/a_{kk}$ e fazer $L_i\leftarrow L_i-m_{ik}L_k$.
3. Substituição regressiva: $x_i=\dfrac{1}{a_{ii}}\Big(b_i-\sum_{j=i+1}^{n-1}a_{ij}x_j\Big)$, de $i=n-1$ até $0$.

Sem pivoteamento, o método falha se algum pivô for zero (ou muito próximo de zero); o código sinaliza esse caso com um erro.

In [2]:
import numpy as np

def gauss_sem_pivoteamento(A, b, verbose=True, tol=1e-12):
    """
    Resolve A x = b por eliminação de Gauss SEM pivoteamento.

    Parâmetros
    ----------
    A : array (n, n)  matriz dos coeficientes
    b : array (n,)    vetor independente
    verbose : bool    se True, exibe a matriz aumentada após cada etapa
    tol : float       tolerância para considerar um pivô nulo

    Retorna
    -------
    x : array (n,)    solução calculada
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).reshape(-1)
    n = A.shape[0]

    # 1) Matriz aumentada [A | b]
    Ab = np.hstack([A, b.reshape(-1, 1)])
    if verbose:
        print("Matriz aumentada inicial:\n", Ab, "\n")

    # 2) Eliminação: zera os elementos abaixo de cada pivô
    for k in range(n - 1):
        pivo = Ab[k, k]
        if abs(pivo) < tol:
            raise ZeroDivisionError(
                f"Pivô nulo na posição ({k},{k}): sem pivoteamento o método falha."
            )
        for i in range(k + 1, n):
            m = Ab[i, k] / pivo          # multiplicador m_ik
            Ab[i, k:] -= m * Ab[k, k:]   # L_i <- L_i - m * L_k
            if verbose:
                print(f"L{i+1} <- L{i+1} - ({m:.4f}) * L{k+1}")
        if verbose:
            print(f"\nApós a etapa {k+1}:\n", Ab, "\n")

    if abs(Ab[n - 1, n - 1]) < tol:
        raise ZeroDivisionError("Último pivô nulo: sistema singular.")

    # 3) Substituição regressiva
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        soma = np.dot(Ab[i, i + 1:n], x[i + 1:n])
        x[i] = (Ab[i, n] - soma) / Ab[i, i]

    return x

**Teste com o sistema do exercício 2** e comparação com `numpy.linalg.solve`:

In [3]:
# Sistema do exercício 2
A2 = np.array([[ 2,  1, -1],
               [-3, -1,  2],
               [-2,  1,  2]], dtype=float)
b2 = np.array([8, -11, -3], dtype=float)

x_gauss = gauss_sem_pivoteamento(A2, b2, verbose=True)   # nossa implementação
x_numpy = np.linalg.solve(A2, b2)                         # referência (LU com pivoteamento parcial)

print("Solução (Gauss manual):       ", x_gauss)
print("Solução (numpy.linalg.solve): ", x_numpy)
print("Diferença máxima |x_gauss - x_numpy|:", np.max(np.abs(x_gauss - x_numpy)))
print("Resíduo ||A x - b||:", np.linalg.norm(A2 @ x_gauss - b2))

Matriz aumentada inicial:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]] 

L2 <- L2 - (-1.5000) * L1
L3 <- L3 - (-1.0000) * L1

Após a etapa 1:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]] 

L3 <- L3 - (4.0000) * L2

Após a etapa 2:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]] 

Solução (Gauss manual):        [ 2.  3. -1.]
Solução (numpy.linalg.solve):  [ 2.  3. -1.]
Diferença máxima |x_gauss - x_numpy|: 5.551115123125783e-16
Resíduo ||A x - b||: 0.0


**Interpretação:** a implementação reproduz a resolução manual do exercício 2, $(x,y,z)=(2,3,-1)$, e concorda com `numpy.linalg.solve` até a precisão de máquina (diferença da ordem de $10^{-15}$) e resíduo praticamente zero. Neste sistema os pivôs encontrados ($2$, $\tfrac12$ e $-1$) são não nulos, então o pivoteamento não foi necessário. Em geral, porém, o `numpy` usa pivoteamento parcial, o que o torna mais robusto: sem pivoteamento, um pivô nulo (ou muito pequeno) causa falha ou amplificação de erros de arredondamento.

## Parte 4 — Aplicação

### Exercício 5 — Modelo de balanço térmico

$$
\begin{bmatrix} 4 & -1 & 0\\ -1 & 4 & -1\\ 0 & -1 & 3 \end{bmatrix}
\begin{bmatrix} T_1\\ T_2\\ T_3 \end{bmatrix}
=
\begin{bmatrix} 15\\ 10\\ 10 \end{bmatrix}
$$

**a) Resolução manual (eliminação de Gauss).**

Matriz aumentada:
$$
\left[\begin{array}{rrr|r}
4 & -1 & 0 & 15\\
-1 & 4 & -1 & 10\\
0 & -1 & 3 & 10
\end{array}\right]
$$

**Etapa 1** — pivô $a_{11}=4$; $m_{21}=-\tfrac14$, $m_{31}=0$:
$L_2\leftarrow L_2+\tfrac14L_1$

$$
\left[\begin{array}{rrr|r}
4 & -1 & 0 & 15\\
0 & \tfrac{15}{4} & -1 & \tfrac{55}{4}\\
0 & -1 & 3 & 10
\end{array}\right]
$$

**Etapa 2** — pivô $a_{22}=\tfrac{15}{4}$; $m_{32}=\dfrac{-1}{15/4}=-\tfrac{4}{15}$:
$L_3\leftarrow L_3+\tfrac{4}{15}L_2$

$$
a_{33}' = 3-\tfrac{4}{15}=\tfrac{41}{15},\qquad
b_3' = 10+\tfrac{4}{15}\cdot\tfrac{55}{4}=10+\tfrac{55}{15}=\tfrac{205}{15}
$$

$$
\left[\begin{array}{rrr|r}
4 & -1 & 0 & 15\\
0 & \tfrac{15}{4} & -1 & \tfrac{55}{4}\\
0 & 0 & \tfrac{41}{15} & \tfrac{205}{15}
\end{array}\right]
$$

**Substituição regressiva:**
$$
\tfrac{41}{15}T_3=\tfrac{205}{15}\;\Rightarrow\;T_3=\tfrac{205}{41}=5
$$
$$
\tfrac{15}{4}T_2-T_3=\tfrac{55}{4}\;\Rightarrow\;\tfrac{15}{4}T_2=\tfrac{55}{4}+5=\tfrac{75}{4}\;\Rightarrow\;T_2=5
$$
$$
4T_1-T_2=15\;\Rightarrow\;4T_1=20\;\Rightarrow\;T_1=5
$$

**Verificação:** $4(5)-5=15$ ✓; $-5+4(5)-5=10$ ✓; $-5+3(5)=10$ ✓

$$
\boxed{T_1=T_2=T_3=5}
$$

**b) Implementação em Python** (reutilizando a função do exercício 4):

In [4]:
# Sistema do balanço térmico
A5 = np.array([[ 4, -1,  0],
               [-1,  4, -1],
               [ 0, -1,  3]], dtype=float)
b5 = np.array([15, 10, 10], dtype=float)

T_gauss = gauss_sem_pivoteamento(A5, b5, verbose=False)  # Gauss implementado
T_numpy = np.linalg.solve(A5, b5)                         # referência

print("T (Gauss manual):       ", T_gauss)
print("T (numpy.linalg.solve): ", T_numpy)
print("Diferença máxima:", np.max(np.abs(T_gauss - T_numpy)))
print("Resíduo ||A T - b||:", np.linalg.norm(A5 @ T_gauss - b5))

T (Gauss manual):        [5. 5. 5.]
T (numpy.linalg.solve):  [5. 5. 5.]
Diferença máxima: 0.0
Resíduo ||A T - b||: 0.0


**Interpretação:** a solução numérica confirma a resolução manual: $T_1=T_2=T_3=5$ (na unidade do problema). A matriz é simétrica, de diagonal dominante e positiva definida, de modo que os pivôs permanecem positivos ($4$, $\tfrac{15}{4}$, $\tfrac{41}{15}$) e a eliminação sem pivoteamento é segura e bem condicionada. O resultado também é fisicamente plausível: as fontes ($15$, $10$, $10$) e as trocas de calor entre nós levam a um equilíbrio com temperaturas iguais.